version: '3.9'

services:
  web-api:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: student-dashboard-web-api
    restart: always
    volumes:
      - /root/Sarvar/DB:/app/DB
      - /root/Sarvar/Files:/app/Files
    ports:
      - "8080:8080"
    networks:
      - student-wep-api-network
  
networks:
  student-wep-api-network:
    driver: bridge